package modelos;
// Generated 26/03/2021 04:27:33 PM by Hibernate Tools 4.3.1



/**
 * Personas generated by hbm2java
 */
public class Personas  implements java.io.Serializable {


     private Integer idpersonas;
     private String nombre;

    public Personas() {
    }

    public Personas(String nombre) {
       this.nombre = nombre;
    }
   
    public Integer getIdpersonas() {
        return this.idpersonas;
    }
    
    public void setIdpersonas(Integer idpersonas) {
        this.idpersonas = idpersonas;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


